### ISSUE TITLE
How do you use the generated file? 

### ISSUE THREAD

**Issue by chardskarth** [LimeBeck/BuildTimeConfig#6]
This library works!

But how can I use the generated source? 

I imagine i should be able to do something like:

```kotlin
kotlin {
    jvmToolchain(17)
    sourceSets {
        main {
            kotlin.srcDir(layout.buildDirectory.get().asFile)
        }
    }
}
```

but I just hardcode

```kotlin
kotlin {
    jvmToolchain(17)
    sourceSets {
        main {
            kotlin.srcDir("build/unnamed")
        }
    }
}

```

**Comment by LimeBeck** [comment]
@chardskarth All generated sources should be automatically added to the `main` source set. If you are unable to import the generated classes into your project, can you provide an example of your project configuration?

**Comment by chardskarth** [comment]
Resolving this. I think I just needed to restart invalidate cache intellj ¯\_(ツ)_/¯
